### ISSUE TITLE
display package version as 1.0 regardless of actual version

### ISSUE THREAD

**Issue by vagrantc** [lamby/buildinfo.debian.net#21]
Presumably due to the update of the .buildinfo file format, buildinfo.debian.net is somehow parsing the "Format" field as the "Version" field, and all .buildinfo files are registering as version "1.0". Just grabbing the first three examples from https://buildinfo.debian.net at the moment:

stress-ng_1.0_arm64.buildinfo from 0xAAA3AE5F86A5D0BA
stress-ng_1.0_arm64.buildinfo from 0x1D3EA4D86F2FB555
libcatalyst-model-adaptor-perl_1.0_all.buildinfo from 0xFAC0B94FFF2617A2 cbxi4b (Automatically generated key for signing .buildinfo files)
libcatalyst-model-adaptor-perl_1.0_all.buildinfo from 0xC7E7F3E4B48B3CE6 opi2b (Automatically generated key for signing .buildinfo files)
envstore_1.0_amd64.buildinfo from 0x1BD40F376E003684 profitbricks-build5-amd64 (Automatically generated key for signing .buildinfo files)

**Comment by lamby** [comment]
```
import datetime
from bidb.buildinfo.models import Buildinfo
Buildinfo.objects.filter(version='1.0', created__gte=datetime.datetime(2017, 3, 23)).delete()
````
