### ISSUE TITLE
API to fetch specific .buildinfo files for a certain package/arch/builder

### ISSUE THREAD

**Issue by h01ger** [lamby/buildinfo.debian.net#25]
h01ger:  lamby: say i want the .buildinfo file for zsh 5.4.2-1 on amd64, how can i get that from buildinfo.debian.net?
lamby: h01ger: https://buildinfo.debian.net/sources/zsh/5.4.2-1 ?
lamby: Note that there isn't "the" .buildinfo - there are (potentially) multiple ones.
lamby: So there isn't a canonical URL for a (src, version, buildarch) tuple that leads to a single buildinfo, it's more (src, ver, arch) → [.buildinfo]
h01ger: | lamby: i think we need such an API, or do you expect consumers (=tools) to scrape those webpages?
<lamby> | h01ger: Obviously avoiding scraping. Please file a wishlist bug if you want an API endpoint for that :)

**Comment by lamby** [comment]
@h01ger 

You mention "builder" in the subject of this issue; can you clarify what you mean there?

**Comment by h01ger** [comment]
On Tue, Oct 24, 2017 at 02:52:53PM +0000, Chris Lamb wrote:
> You mention "builder" in the subject of this issue; can you clarify what you mean there?

good catch! :)

with "builder" I ment something like "everything that went to ftp.debian.org"
and then I realized that this wont be one builder but many…

and as that (=figuring out what this means in the Debian case, and in
general) aint easy (and because I'm at a conf) I conviniently forgot
about this "little" problem.

so to sum up, sometimes I might want to be able to specificy the
builder, but probably more often the "scope" or something.

I'm also thinking about rebuilders feeding data into b.d.n, eg the
famous NASA rebuilding all of Debian and submitting these results to
b.d.n as well, then I want to be able to say:

"give me that buildinfo file for zsh 5.4.2-1 on arm64 from ftp.d.o"

or

"give me that buildinfo file for zsh 5.4.2-1 on arm64 from NASA"

i dont really want to deal with knowing how the buildhosts / signing
keys are called. or maybe thats the way, gpg keyrings:

"give me that buildinfo file (or those files) for zsh 5.4.2-1 on arm64
signed by any keys in debian-builders.keyring".


-- 
cheers,
	Holger

**Comment by lamby** [comment]
eg. https://buildinfo.debian.net/api/v1/sources/minicom/2.7.1-1/arm64

**Comment by h01ger** [comment]
I'd like to reopen this bug, but it seems I cannot. 

https://buildinfo.debian.net/api/v1/sources/minicom/2.7.1-1/arm64 returns some json data, but not single .buildinfo file :(

I'd like to be able to query the .buildinfo file as used for the Debian archive… this is still not possible.

**Comment by lamby** [comment]
@h01ger 

> returns some json data, but not single .buildinfo file :(

I think there is some misunderstanding here, there are multiple .buildinfo files for each (source, version, architecture) 3-tuple. How is it meant to magically know which you want? :) If you could provide examples of the input/output you are after, that would be perfect.

**Comment by h01ger** [comment]
as said, by "give me that buildinfo file (or those files) for zsh 5.4.2-1 on arm64 signed by any keys in debian-builders.keyring".

**Comment by lamby** [comment]
@h01ger  Where does debian-builders.keyring come from? I'd love to nail down the exact inputs :)  

Perhaps something like:

```https://buildinfo.debian.net/api/v1/sources/minicom/2.7.1-1/arm64?uid=0xBUILDER1&uid=0xBUILDER2``` ?

**Comment by h01ger** [comment]
On Fri, Oct 27, 2017 at 03:06:06PM +0000, Chris Lamb wrote:
> @h01ger  Where does debian-builders.keyring come from?

that still needs to be defined ;-)

> I'd love to nail down the exact inputs :)  
 
for sure!

> Perhaps something like:
> ```https://buildinfo.debian.net/api/v1/sources/minicom/2.7.1-1/arm64?uid=0xBUILDER1&uid=0xBUILDER2``` ?

I suppose that wont scale: tests.r-b.o has 48 builders and Debian
probably as many… that's why I came up with the keyring idea…


-- 
cheers,
	Holger

**Comment by lamby** [comment]
Sure, although it would be far cleaner if the server never needed to have the builders keyring stored on it as it would require permission checking to update it, etc etc. :)

> I suppose that wont scale

``GET`` requests can scale really quite far, but just in case we could ``POST`` the filters instead. :)

**Comment by h01ger** [comment]
On Fri, Oct 27, 2017 at 06:35:29PM +0000, Chris Lamb wrote:
> Sure, although it would be far cleaner if the server never needed to have the builders keyring stored on it as it would require permission checking to update it, etc etc. :)

well, "cleaner" is relative too…

> ``GET`` requests can scale really quite far, but just in case we could ``POST`` the filters instead. :)

I'd consider this quite dirty and rather consider server based keyrings
a much cleaner solution. After all, we wont have that many of these
keyrings…


-- 
cheers,
	Holger

**Comment by lamby** [comment]
I've been thinking about this for a few days and I don't think server-based keyrings are the way to go, especially after Intri made an excellent point that this should not be a single point of failure and would further need to be mirrored for performance, etc. and thus we would be introducing the idea of a "privileged" mirror. Having server keyrings would also require some parts of the interface to be password protected in some way adding authentication of some kind to ``buildinfo.debian.net`` that I'd rather avoid until we 200% need it or at least have multiple compelling reasons to add it. Anyway, let's try without server keyrings and see how we get on..

(Still need to implement the uid filtering...)
