### ISSUE TITLE
ability to search for buildinfo's by hash

### ISSUE THREAD

**Issue by vagrantc** [lamby/buildinfo.debian.net#26]
As a correlary to:

https://buildinfo.debian.net/binaries/u-boot
https://buildinfo.debian.net/sources/u-boot

Where you can search for buildinfo files based on binary package or source package, it would be nice if I could search for all buildinfo's containing certain hashes:

e.g. https://buildinfo.debian.net/by-hash/c9070da17f8dd59c9c09698add69453b7c78270b

It would either autodetect the hash type based on length, or possibly an alternate URL form to specify the hash type:

https://buildinfo.debian.net/by-hash/sha1/c9070da17f8dd59c9c09698add69453b7c78270b

This should produce a list of links to .buildinfo that contain the hash of the binary packages (.deb) or "other checksums" (.dsc, .orig.tar.*, debian.tar.*). The above example links should provide a link to the following buildinfo, and possibly others:

https://buildinfo.debian.net/71a17701cd1b1b49dcbee51ae364d3bf8d6f7c10/u-boot_2016.09+dfsg1-2_amd64

The output produced by the binary package view "Generated by source packages" section should be sufficient to convey the desired information. There's some theoretical possibility that differing source/binary packages would produce the same hashes, but it doesn't seem very likely... but would be very interesting to find if that were so!

Hopefully that's enough to go on!

**Comment by lamby** [comment]
@vagrantc 

> https://buildinfo.debian.net/by-hash/sha1/c9070da17f8dd59c9c09698add69453b7c78270b
>
> This should produce a list of links to .buildinfo that contain the hash of [artifacts]

I'd want to clarify in the URI that it's doing a search for the artifacts, not buildinfo files. How about ``/artifacts/by-sha1/c9070da17f8dd59c9c09698add69453b7c78270b/`` ?

**Comment by vagrantc** [comment]
works for me!

**Comment by lamby** [comment]
@vagrantc By search, do you want JSON or HTML? :)

**Comment by vagrantc** [comment]
Well, I was originally just thinking html, but since you brought up json, it would *obviously* be nice to have both! :)

Guess that would require another url, though... is there an /api/ namespace or something like that already? json seems like something that would go in such an "api".

**Comment by lamby** [comment]
@vagrantc Ignoring the URI for now, can you provide the rough (JSON) output you are after. That will ensure we are definitely talking about the right things, as well as "complete" this bug in the sense of "when I do X I want to get Y..."
