### ISSUE TITLE
please default to showing sha256 hashes

### ISSUE THREAD

**Issue by vagrantc** [lamby/buildinfo.debian.net#27]
Currently, it looks like buildinfo.debian.net defaults to exposing sha1 hashes:

https://buildinfo.debian.net/f5c517c5f165b048b70158666f98ecf42cefb0f0/u-boot_2017.09+dfsg1-3_armhf

But it would be nicer to display sha256, which I think is the strongest hash that dpkg-buildpackage generates by default, is what is exposed in the Packages files in the debian.org package archives.

Thanks!

**Comment by lamby** [comment]
Hi @vagrantc 

On https://buildinfo.debian.net/f5c517c5f165b048b70158666f98ecf42cefb0f0/u-boot_2017.09+dfsg1-3_armhf I see the SHA256. Could you clarify where you are missing the SHA256? :)

**Comment by vagrantc** [comment]
When I go to the URL:

https://buildinfo.debian.net/f5c517c5f165b048b70158666f98ecf42cefb0f0/u-boot_2017.09+dfsg1-3_armhf

I only see references to SHA1 on that page:

[buildinfo.d.n-sha1-only.pdf](https://github.com/lamby/buildinfo.debian.net/files/1417000/buildinfo.d.n-sha1-only.pdf)

It displays the "SHA1 of buildinfo" and only SHA1 for all of the various binary artifacts.

If I go to: https://buildinfo.debian.net/f5c517c5f165b048b70158666f98ecf42cefb0f0/u-boot_2017.09+dfsg1-3_armhf.buildinfo

I of course see Checksums-Md5, Checksums-Sha1 and Checksums-Sha256, as it appears to be displaying the actual .buildinfo file or file contents.

**Comment by lamby** [comment]
> I only see references to SHA1 on that page:

Oh, somewhat hiliarously you need a wider screen resolution to see that by default. I think it was looking very ugly for me.  If you dig into the HTML source you can see it's doing some magic...

Anyway, will fix...

**Comment by vagrantc** [comment]
hah! I decreased the font size a bit and it showed up. Ok, that makes some sense, although my screen size isn't exactly small (1920x1080).

**Comment by h01ger** [comment]
yeah, drop sha1…

**Comment by lamby** [comment]
> yeah, drop sha1…

FYI dropping sha1 in buildinfo.debian.net is a somewhat separate issue - it's currently used internally as the quality operator between files. Can be changed, but a different issue to this one which is AUIU "just" a presentation issue (which is totally valid).

**Comment by h01ger** [comment]
On Thu, Oct 26, 2017 at 11:49:45AM +0000, Chris Lamb wrote:
> FYI dropping sha1 in buildinfo.debian.net is a somewhat separate issue - it's currently used internally as the quality operator between files. Can be changed, but a different issue to this one which is AUIU "just" a presentation issue (which is totally valid).

sure!


-- 
cheers,
	Holger
