### ISSUE TITLE
Don't assume that all checkums are .deb packages

### ISSUE THREAD

**Issue by mapreri** [lamby/buildinfo.debian.net#8]
Several packages builds something that is not a .deb, going through the pretty common .udeb, to more [exotic files](https://tracker.debian.org/news/793577).  Please accept them too instead of failing with an error on the POST.

**Comment by lamby** [comment]
(Github should not have closed this.)

**Comment by lamby** [comment]
https://github.com/lamby/buildinfo.debian.net/commit/0559940e38d8df75a7ecbbbd4b4b0d5d247582de does  not fix #8 yet, but will need to rework the binary/artifact distinction first.
